"""add categories

Revision ID: 1188ba47631d
Revises: 2306c0c939f5
Create Date: 2025-12-09 23:29:45.056819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1188ba47631d'
down_revision: Union[str, Sequence[str], None] = '2306c0c939f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories_in_topic')
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'categories', ['category_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    op.create_table('categories_in_topic',
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('categories_in_topic_category_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name=op.f('categories_in_topic_topic_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'category_id', name=op.f('categories_in_topic_pkey'))
    )
    # ### end Alembic commands ###
