"""user add is_root flag

Revision ID: 2306c0c939f5
Revises: 002_add_fks
Create Date: 2025-10-21 07:12:05.075162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2306c0c939f5'
down_revision: Union[str, Sequence[str], None] = '002_add_fks'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ap_value', schema=None) as batch_op:
        batch_op.alter_column('override',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('application_parameters', schema=None) as batch_op:
        batch_op.alter_column('kind',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('gap', 'lap', name='ap_kind', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('datetime', 'integer', 'string', 'float', 'bool', 'list', 'uuid', 'url', name='ap_type', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('visibility',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('public', 'protected', 'private', name='ap_visibility', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.alter_column('action_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('create', 'update', 'delete', name='actiontype', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('audit_effected_objects', schema=None) as batch_op:
        batch_op.alter_column('object_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('user', 'topic', 'topic_translation', 'translation_types', 'category', 'tag', 'topic_link', 'jwt_token', name='objecttype', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('display_mode',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('standard', 'wiki', name='displaymode', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('jwt_tokens', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('is_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('media_object', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False))
        batch_op.alter_column('obj_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('user_avatar', 'system', 'topic', name='mediatype', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('has_small',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('has_medium',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('has_large',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('edited_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
        batch_op.alter_column('creator_user_id',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('topic_links', schema=None) as batch_op:
        batch_op.alter_column('away',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('topic_translations', schema=None) as batch_op:
        batch_op.alter_column('creator_user_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.alter_column('parse_mode',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('markdown', 'bbcode', name='parsemode', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('last_edited_by',
               existing_type=sa.UUID(),
               nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_root', sa.Boolean(), nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('admin', 'user', 'moderator', name='userroles', native_enum=False),
               existing_nullable=False)
        batch_op.alter_column('is_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('force_password_change',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('force_password_change',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('is_disabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.Enum('admin', 'user', 'moderator', name='userroles', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('is_root')

    with op.batch_alter_table('topic_translations', schema=None) as batch_op:
        batch_op.alter_column('last_edited_by',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('parse_mode',
               existing_type=sa.Enum('markdown', 'bbcode', name='parsemode', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('creator_user_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('topic_links', schema=None) as batch_op:
        batch_op.alter_column('away',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.alter_column('creator_user_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('edited_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)

    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('media_object', schema=None) as batch_op:
        batch_op.alter_column('has_large',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('has_medium',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('has_small',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('obj_type',
               existing_type=sa.Enum('user_avatar', 'system', 'topic', name='mediatype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('uploaded_at')

    with op.batch_alter_table('jwt_tokens', schema=None) as batch_op:
        batch_op.alter_column('is_revoked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.UUID(),
               nullable=True)

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.alter_column('display_mode',
               existing_type=sa.Enum('standard', 'wiki', name='displaymode', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('audit_effected_objects', schema=None) as batch_op:
        batch_op.alter_column('object_type',
               existing_type=sa.Enum('user', 'topic', 'topic_translation', 'translation_types', 'category', 'tag', 'topic_link', 'jwt_token', name='objecttype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('audit', schema=None) as batch_op:
        batch_op.alter_column('action_type',
               existing_type=sa.Enum('create', 'update', 'delete', name='actiontype', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('application_parameters', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.Enum('public', 'protected', 'private', name='ap_visibility', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.Enum('datetime', 'integer', 'string', 'float', 'bool', 'list', 'uuid', 'url', name='ap_type', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.alter_column('kind',
               existing_type=sa.Enum('gap', 'lap', name='ap_kind', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('ap_value', schema=None) as batch_op:
        batch_op.alter_column('override',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
