"""updated root_user storing

Revision ID: 4e9dce5e4abc
Revises: 69c88c7310f6
Create Date: 2025-12-10 22:09:00.116965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e9dce5e4abc'
down_revision: Union[str, Sequence[str], None] = '69c88c7310f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application_parameters', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('public', 'system', 'private', name='ap_visibility', native_enum=False),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_root')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_root', sa.BOOLEAN(), autoincrement=False, nullable=False))

    with op.batch_alter_table('application_parameters', schema=None) as batch_op:
        batch_op.alter_column('visibility',
               existing_type=sa.Enum('public', 'system', 'private', name='ap_visibility', native_enum=False),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###
