"""topic_entity

Revision ID: 6b68a8f112e4
Revises: b0fdbdd8e5c7
Create Date: 2026-05-10 12:11:06.244402

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b68a8f112e4'
down_revision: Union[str, Sequence[str], None] = 'b0fdbdd8e5c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_entity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('translation_name', sa.String(length=200), nullable=False),
    sa.Column('topic_name', sa.String(length=200), nullable=False),
    sa.Column('community', sa.Boolean(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('translation_code_id', sa.Integer(), nullable=False),
    sa.Column('cover_image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cover_image_id'], ['media_object.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['translation_code_id'], ['translations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id')
    )
    op.create_table('translated_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('translation_entity_id', sa.Integer(), nullable=False),
    sa.Column('internal_block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['media_object.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['translation_entity_id'], ['translation_entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translated_text',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('translation_entity_id', sa.Integer(), nullable=False),
    sa.Column('internal_block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['translation_entity_id'], ['translation_entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('audit_effected_objects')
    op.drop_table('topic_links')
    op.drop_table('tags_in_topic')
    op.drop_table('audit')
    with op.batch_alter_table('media_object', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_media_object_used_topic'), type_='foreignkey')
        batch_op.drop_column('used_topic_id')

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('json_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
        batch_op.add_column(sa.Column('basic_langage_t_code_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('topic_name_hash_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('fk_topic_cover_image'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'translations', ['basic_langage_t_code_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('cover_image_id')
        batch_op.drop_column('name_hash')
        batch_op.drop_column('imported')
        batch_op.drop_column('name')

    with op.batch_alter_table('topic_translations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('json_text', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
        batch_op.drop_column('parse_mode')
        batch_op.drop_column('text')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic_translations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('parse_mode', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
        batch_op.drop_column('json_text')

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('imported', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name_hash', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cover_image_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_topic_cover_image'), 'media_object', ['cover_image_id'], ['id'], ondelete='SET NULL')
        batch_op.create_unique_constraint(batch_op.f('topic_name_hash_key'), ['name_hash'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('basic_langage_t_code_id')
        batch_op.drop_column('json_structure')

    with op.batch_alter_table('media_object', schema=None) as batch_op:
        batch_op.add_column(sa.Column('used_topic_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_media_object_used_topic'), 'topic', ['used_topic_id'], ['id'], ondelete='SET NULL')

    op.create_table('audit',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action_type', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_pkey'))
    )
    op.create_table('tags_in_topic',
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('tags_in_topic_tag_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name=op.f('tags_in_topic_topic_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'tag_id', name=op.f('tags_in_topic_pkey'))
    )
    op.create_table('topic_links',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('link_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('link_url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('away', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], name=op.f('topic_links_topic_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('topic_links_pkey'))
    )
    op.create_table('audit_effected_objects',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('audit_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('object_type', sa.VARCHAR(length=17), autoincrement=False, nullable=False),
    sa.Column('object_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['audit_id'], ['audit.id'], name=op.f('audit_effected_objects_audit_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_effected_objects_pkey'))
    )
    op.drop_table('translated_text')
    op.drop_table('translated_image')
    op.drop_table('translation_entity')
    # ### end Alembic commands ###
