"""initial database

Revision ID: 7fc605dc752f
Revises: 
Create Date: 2026-06-07 02:09:59.420552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fc605dc752f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('gap', 'lap', name='ap_kind', native_enum=False), nullable=False),
    sa.Column('type', sa.Enum('datetime', 'integer', 'string', 'float', 'bool', 'json', 'uuid', 'url', name='ap_type', native_enum=False), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'system', 'private', name='ap_visibility', native_enum=False), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_parameters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_parameters_name'), ['name'], unique=True)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('display_mode', sa.Enum('standard', 'wiki', name='displaymode', native_enum=False), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('schedulable_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pretty_name', sa.Text(), nullable=False),
    sa.Column('task_name', sa.Text(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_execution', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_name')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('translation_code',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('translation_code', sa.String(length=2), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_code', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_code_translation_code'), ['translation_code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('registration_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', 'moderator', name='userroles', native_enum=False), nullable=False),
    sa.Column('is_disabled', sa.Boolean(), nullable=False),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ap_value',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('override', sa.Boolean(), nullable=False),
    sa.Column('ap_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ap_id'], ['application_parameters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jwt_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used', sa.DateTime(timezone=True), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('on_creation_ip', sa.String(length=45), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_object',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('obj_type', sa.Enum('user_avatar', 'system', 'topic', name='mediatype', native_enum=False), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sha256_hash_original', sa.String(length=64), nullable=False),
    sa.Column('sha256_hash_thumb', sa.String(length=64), nullable=False),
    sa.Column('sha256_hash_small', sa.String(length=64), nullable=True),
    sa.Column('sha256_hash_medium', sa.String(length=64), nullable=True),
    sa.Column('sha256_hash_large', sa.String(length=64), nullable=True),
    sa.Column('has_small', sa.Boolean(), nullable=False),
    sa.Column('has_medium', sa.Boolean(), nullable=False),
    sa.Column('has_large', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(), nullable=False),
    sa.Column('used_user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['used_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256_hash_large'),
    sa.UniqueConstraint('sha256_hash_medium'),
    sa.UniqueConstraint('sha256_hash_original'),
    sa.UniqueConstraint('sha256_hash_small'),
    sa.UniqueConstraint('sha256_hash_thumb')
    )
    op.create_table('topic',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('creator_user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('json_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('basic_langage_t_code_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basic_langage_t_code_id'], ['translation_code.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('translation_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('creator_user_id', sa.UUID(), nullable=False),
    sa.Column('last_edited_by', sa.UUID(), nullable=False),
    sa.Column('json_text', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_edited_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['translation_id'], ['translation_code.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translation_entity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('translation_name', sa.String(length=200), nullable=False),
    sa.Column('topic_name', sa.String(length=200), nullable=False),
    sa.Column('community', sa.Boolean(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('translation_code_id', sa.Integer(), nullable=False),
    sa.Column('cover_image_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cover_image_id'], ['media_object.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['translation_code_id'], ['translation_code.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id')
    )
    op.create_table('translated_image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('translation_entity_id', sa.Integer(), nullable=False),
    sa.Column('internal_block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['media_object.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['translation_entity_id'], ['translation_entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translated_text',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('translation_entity_id', sa.Integer(), nullable=False),
    sa.Column('internal_block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['translation_entity_id'], ['translation_entity.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('translated_text')
    op.drop_table('translated_image')
    op.drop_table('translation_entity')
    op.drop_table('topic_translations')
    op.drop_table('topic')
    op.drop_table('media_object')
    op.drop_table('jwt_tokens')
    op.drop_table('ap_value')
    op.drop_table('users')
    with op.batch_alter_table('translation_code', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_code_translation_code'))

    op.drop_table('translation_code')
    op.drop_table('tags')
    op.drop_table('schedulable_task')
    op.drop_table('categories')
    with op.batch_alter_table('application_parameters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_parameters_name'))

    op.drop_table('application_parameters')
    # ### end Alembic commands ###
