"""application parameters, media

Revision ID: 99b5c52e9506
Revises: b9961c31d1b6
Create Date: 2025-10-19 05:41:26.689901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99b5c52e9506'
down_revision: Union[str, Sequence[str], None] = 'b9961c31d1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_parameters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('gap', 'lap', name='ap_kind', native_enum=False), nullable=False),
    sa.Column('type', sa.Enum('datetime', 'integer', 'string', 'float', 'bool', 'list', 'uuid', 'url', name='ap_type', native_enum=False), nullable=False),
    sa.Column('visibility', sa.Enum('public', 'protected', 'private', name='ap_visibility', native_enum=False), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('application_parameters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_application_parameters_name'), ['name'], unique=True)

    op.create_table('media_object',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obj_type', sa.Enum('user_avatar', 'system', 'topic', name='mediatype', native_enum=False), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sha256_hash_original', sa.String(length=64), nullable=False),
    sa.Column('sha256_hash_thumb', sa.String(length=64), nullable=False),
    sa.Column('sha256_hash_small', sa.String(length=64), nullable=True),
    sa.Column('sha256_hash_medium', sa.String(length=64), nullable=True),
    sa.Column('sha256_hash_large', sa.String(length=64), nullable=True),
    sa.Column('has_small', sa.Boolean(), nullable=False),
    sa.Column('has_medium', sa.Boolean(), nullable=False),
    sa.Column('has_large', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.Integer(), nullable=False),
    sa.Column('used_topic_id', sa.Integer(), nullable=True),
    sa.Column('used_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['used_topic_id'], ['topic.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['used_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256_hash_large'),
    sa.UniqueConstraint('sha256_hash_medium'),
    sa.UniqueConstraint('sha256_hash_original'),
    sa.UniqueConstraint('sha256_hash_small'),
    sa.UniqueConstraint('sha256_hash_thumb')
    )
    op.create_table('ap_value',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('override', sa.Boolean(), nullable=False),
    sa.Column('ap_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ap_id'], ['application_parameters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_image_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'media_object', ['cover_image_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('cover_image_id')

    op.drop_table('ap_value')
    op.drop_table('media_object')
    with op.batch_alter_table('application_parameters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_application_parameters_name'))

    op.drop_table('application_parameters')
    # ### end Alembic commands ###
