"""add tasks

Revision ID: b0fdbdd8e5c7
Revises: 4e9dce5e4abc
Create Date: 2025-12-22 07:47:14.280758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0fdbdd8e5c7'
down_revision: Union[str, Sequence[str], None] = '4e9dce5e4abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedulable_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('pretty_name', sa.Text(), nullable=False),
    sa.Column('task_name', sa.Text(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_execution', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedulable_task')
    # ### end Alembic commands ###
