"""static media

Revision ID: b33acbdd28a7
Revises: b9961c31d1b6
Create Date: 2025-10-16 23:24:06.033566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b33acbdd28a7'
down_revision: Union[str, Sequence[str], None] = 'b9961c31d1b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('cover_image_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'topic', 'media_object', ['cover_image_id'], ['id'], ondelete='SET NULL')
    op.drop_column('topic', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'topic', type_='foreignkey')
    op.drop_column('topic', 'cover_image_id')
    # ### end Alembic commands ###
